module.exports = {
  DIRECTLINE_ORCHESTRATOR_TOKEN_CID: 'DIRECTLINE_ORCHESTRATOR_TOKEN_CID',
  DIRECTLINE_ORCHESTRATOR_TOKEN_URL: 'DIRECTLINE_ORCHESTRATOR_TOKEN_URL',
  DIRECTLINE_ORCHESTRATOR_CONVERSATIONS_URL: 'DIRECTLINE_ORCHESTRATOR_CONVERSATIONS_URL',
  DIRECTLINE_ORCHESTRATOR_CID: 'DIRECTLINE_ORCHESTRATOR_CID',
  DIRECTLINE_ORCHESTRATOR_USER_AGENT: 'DIRECTLINE_ORCHESTRATOR_USER_AGENT',
  DIRECTLINE_ORCHESTRATOR_AUTH: 'DIRECTLINE_ORCHESTRATOR_AUTH',
  DIRECTLINE_ORCHESTRATOR_XPTWJ: 'DIRECTLINE_ORCHESTRATOR_XPTWJ',
  DIRECTLINE_ORCHESTRATOR__PX3: 'DIRECTLINE_ORCHESTRATOR__PX3',
  DIRECTLINE_ORCHESTRATOR_GENERATE_USERNAME: 'DIRECTLINE_ORCHESTRATOR_GENERATE_USERNAME',
  DIRECTLINE_ORCHESTRATOR_HANDLE_ACTIVITY_TYPES: 'DIRECTLINE_ORCHESTRATOR_HANDLE_ACTIVITY_TYPES',
  DIRECTLINE_ORCHESTRATOR_WELCOME_ACTIVITY: 'DIRECTLINE_ORCHESTRATOR_WELCOME_ACTIVITY',
  // Websocket
  DIRECTLINE_ORCHESTRATOR_WEBSOCKET_HANDSHAKE_TIMEOUT: 'DIRECTLINE_ORCHESTRATOR_WEBSOCKET_HANDSHAKE_TIMEOUT',
  // Directline3
  DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_ACTIVITY_TEMPLATE: 'DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_ACTIVITY_TEMPLATE',
  DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_BUTTON_TYPE: 'DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_BUTTON_TYPE',
  DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_BUTTON_VALUE_FIELD: 'DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_BUTTON_VALUE_FIELD',
  DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_ACTIVITY_VALIDATION: 'DIRECTLINE_ORCHESTRATOR_DIRECTLINE3_ACTIVITY_VALIDATION'

}
